#! /bin/bash

if [ $1 == 'help' ]; then
	echo "Usage:"
	echo "s3-jekyll-deploy BUCKET_NAME"
	exit 0
fi;

BUCKET=$1
TMP_DIR="/tmp/s3-jekyll-deploy/"
HASH_LIST="$TMP_DIR/$BUCKET"

if [ ! -d $TMP_DIR ]; then
	mkdir $TMP_DIR;
	touch $HASH_LIST;
fi;

MD5=/usr/bin/md5sum

if [ ! -f $MD5  ]; then
	MD5="/sbin/md5 -r"
fi;

cd _site

typeFor(){
        TYPE=`echo $1 | sed -E "s/.+\.([^$]+)$/\1/"`
        CONTENT_TYPE="text/plain"
        if [ $TYPE == "htm" ]; then CONTENT_TYPE="text/html"; fi;
        if [ $TYPE == "html" ]; then CONTENT_TYPE="text/html"; fi;
        if [ $TYPE == "txt" ]; then CONTENT_TYPE="text/plain"; fi;
        if [ $TYPE == "xml" ]; then CONTENT_TYPE="application/xml"; fi;
        if [ $TYPE == "css" ]; then CONTENT_TYPE="text/css"; fi;
        if [ $TYPE == "js" ]; then CONTENT_TYPE="text/javascript"; fi;
        if [ $TYPE == "png" ]; then CONTENT_TYPE="image/png"; fi;
        if [ $TYPE == "PNG" ]; then CONTENT_TYPE="image/png"; fi;
        if [ $TYPE == "jpg" ]; then CONTENT_TYPE="image/jpg"; fi;
        if [ $TYPE == "JPG" ]; then CONTENT_TYPE="image/jpg"; fi;
        if [ $TYPE == "gif" ]; then CONTENT_TYPE="image/gif"; fi;
        if [ $TYPE == "ico" ]; then CONTENT_TYPE="image/x-icon"; fi;
        if [ $TYPE == "zip" ]; then CONTENT_TYPE="application/zip"; fi;
        if [ $TYPE == "gz" ]; then CONTENT_TYPE="application/gzip"; fi;
        if [ $TYPE == "pdf" ]; then CONTENT_TYPE="application/pdf"; fi;
}

for FILE in `find . -type f`; do
	HASH=$($MD5 $FILE | cut -d" " -f 1)
	if ! grep -Fxq $HASH $HASH_LIST ; then
		S3_NAME=$(echo $FILE | sed -E "s/\.\///")
		echo "Deploying $S3_NAME"
        typeFor $FILE
        ~/bin/aws/aws put "x-amz-acl: public-read" "Content-Type: $CONTENT_TYPE" $BUCKET $S3_NAME;
		echo $HASH >> $HASH_LIST
	fi;
done;

echo "Deploy terminado"

cd ..
